version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running HTML linting...
      - npm install -g htmlhint
      - htmlhint public/index.html
  build:
    commands:
      - echo Running unit tests...
      - npm test
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  discard-paths: yes
